name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 22.17.0
  APP_DIR: my-next-app

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure package-lock.json exists
        run: |
          test -f package-lock.json || {
            echo "Error: package-lock.json is required when using npm ci"
            exit 1
          }

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: ${{ env.APP_DIR }}/.next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
